import { ReactNode } from "react";
import Head from "next/head";

import SiteHeader from "@/src/components/blog/siteheader";
import SiteFooter from "@/src/components/blog/sitefooter";

interface LayoutProps {
  children?: ReactNode;
}

export default function Layout({ children }: LayoutProps): JSX.Element {


  return (
    <>
      <Head>
        <title>Blog Search</title>
        <meta name="description" content="Generated by Lewis Liu" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader className="header-blog-home z-10 relative" />

      <div>{children}</div>

      <SiteFooter />
    </>
  );
}
